apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-declarative
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-declarative  # Consistent with template
  template:
    metadata:
      labels:
        app: nginx-declarative  # Consistent with selector
    spec:
      containers:
      - name: nginx
        image: nginx:latest  # Specified tag for stability
        ports:
        - containerPort: 443
          name: http  # Named port for service mapping
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        securityContext:
          runAsNonRoot: true
          runAsUser: 101
          privileged: false
        livenessProbe:  # Detects and restarts unhealthy pods
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:  # Ensures pods are ready
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
