apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-declarative
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-declarative  # Updated to match template labels
  template:
    metadata:
      labels:
        app: nginx-declarative  # Updated for consistency
    spec:
      containers:
      - name: nginx
        image: nginx:latest  # Specified tag for stability
        ports:
        - containerPort: 80
          name: http  # Named port for service mapping
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        securityContext:
          runAsNonRoot: true
          runAsUser: 101
          privileged: false
        livenessProbe:  # Added to detect and restart unhealthy pods
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:  # Added to ensure pods are ready to serve traffic
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
      # Optional: Add tolerations or nodeSelector if needed for specific node health
