#Content in deployment.yaml file OLD VERSION:-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-declarative
  namespace: default  # Add this line
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-declarative
  template:
    metadata:
      labels:
        app: nginx-declarative
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
